# Generated by Django 5.0.6 on 2024-09-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_user', models.TextField(unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.TextField(unique=True)),
                ('mobile_no', models.CharField(unique=True)),
                ('password_hash', models.TextField()),
            ],
            options={
                'db_table': 'ums_user_model',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refresh_user', to='ManagementMicroservice.usermodel')),
            ],
            options={
                'db_table': 'ums_refresh_token',
            },
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_user', models.TextField(unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_item', to='ManagementMicroservice.usermodel')),
            ],
            options={
                'db_table': 'ums_inventory_model',
            },
        ),
    ]
